name: MythicalSystemsUtils
version: '${project.version}'
main: xyz.mythicalsystems.mythicalsystemsutils.MythicalSystemsUtils
load: STARTUP
authors: [NaysKutzu]
description: A a simple lib / integration minecraft plugin for mythicalsystems tools :)!
website: https://mythicalsystems.xyz
softdepend: [Vault, PlaceholderAPI]
depend: [LuckPerms]
commands:
  console:
    description: Execute commands into the server console
    aliases: [svc, cex, c]
  mythicalsystemsutils:
    description: The main command for MythicalSystemsUtils!
    aliases: [msu]
  chatformatter:
    aliases: [lpc, ctf]
permissions:
  mythicalsystemsutils.version:
    description: See the version of the plugin
  mythicalsystemsutils.help:
    description: Get help with the plugin
  mythicalsystemsutils.author:
    description: See who made the plugin
  mythicalsystemsutils.colorcodes:
    description: Allows players to type in chat with colors!
  mythicalsystemsutils.rgbcodes:
    description: Allows you to type in the chat with RGB codes!

  mythicalsystemsutils.*:
    description: Gives access to all mythicalsystemsutils core commands!
    children:
      mythicalsystemsutils.version: true
      mythicalsystemsutils.help: true
      mythicalsystemsutils.author: true
      mythicalsystemsutils.rgbcodes: true
      mythicalsystemsutils.colorcodes: true